#!/bin/sh -e

set -e

. /usr/share/debconf/confmodule

db_fset {{package_name}}/host hidden false
db_fset {{package_name}}/port hidden false
db_fset {{package_name}}/machinekey hidden false
db_input low {{package_name}}/host || true
db_input low {{package_name}}/port || true
db_input low {{package_name}}/machinekey || true
db_go

# OpenSearch
db_input low {{package_name}}/elasticsearch-host || true
db_go
db_get {{package_name}}/elasticsearch-host
if [ -n "$RET" ] && [ "$RET" != "localhost" ]; then
    db_fset {{package_name}}/elasticsearch-scheme hidden false
    db_fset {{package_name}}/elasticsearch-port hidden false
    db_input high {{package_name}}/elasticsearch-scheme || true
    db_input high {{package_name}}/elasticsearch-port || true
    db_go
else
    db_fset {{package_name}}/elasticsearch-scheme hidden true
    db_fset {{package_name}}/elasticsearch-port hidden true
fi

# Redis
db_input low {{package_name}}/redis-host || true
db_go
db_get {{package_name}}/redis-host
if [ -n "$RET" ] && [ "$RET" != "localhost" ]; then
    db_fset {{package_name}}/redis-port hidden false
    db_fset {{package_name}}/redis-username hidden false
    db_fset {{package_name}}/redis-db hidden false
    db_fset {{package_name}}/redis-password hidden false
    db_input high {{package_name}}/redis-port || true
    db_input high {{package_name}}/redis-username || true
    db_input high {{package_name}}/redis-db || true
    db_input critical {{package_name}}/redis-password || true
    db_go
else
    db_fset {{package_name}}/redis-port hidden true
    db_fset {{package_name}}/redis-username hidden true
    db_fset {{package_name}}/redis-db hidden true
    db_fset {{package_name}}/redis-password hidden true
fi

# RabbitMQ
db_input low {{package_name}}/rabbitmq-host || true
db_go
db_get {{package_name}}/rabbitmq-host
if [ -n "$RET" ] && [ "$RET" != "localhost" ]; then
    db_fset {{package_name}}/rabbitmq-protocol hidden false
    db_fset {{package_name}}/rabbitmq-port hidden false
    db_fset {{package_name}}/rabbitmq-user hidden false
    db_fset {{package_name}}/rabbitmq-password hidden false
    db_input high {{package_name}}/rabbitmq-protocol || true
    db_input high {{package_name}}/rabbitmq-port || true
    db_input high {{package_name}}/rabbitmq-user || true
    db_input critical {{package_name}}/rabbitmq-password || true
    db_go
else
    db_fset {{package_name}}/rabbitmq-protocol hidden true
    db_fset {{package_name}}/rabbitmq-port hidden true
    db_fset {{package_name}}/rabbitmq-user hidden true
    db_fset {{package_name}}/rabbitmq-password hidden true
fi

# Database
db_input low {{package_name}}/db-host || true
db_go
db_get {{package_name}}/db-host
if [ -n "$RET" ] && [ "$RET" != "localhost" ]; then
    db_fset {{package_name}}/db-name hidden false
    db_fset {{package_name}}/db-user hidden false
    db_fset {{package_name}}/db-pwd hidden false
    db_input high {{package_name}}/db-port || true
    db_input high {{package_name}}/db-name || true
    db_input high {{package_name}}/db-user || true
    db_input critical {{package_name}}/db-pwd || true
    db_go
else
    db_fset {{package_name}}/db-name hidden true
    db_fset {{package_name}}/db-user hidden true
    db_fset {{package_name}}/db-pwd hidden true
fi

# External Docs
db_input low {{package_name}}/ds-url || true
db_go
db_get {{package_name}}/ds-url
if [ -n "$RET" ] && [ "$RET" != "localhost" ]; then
    db_fset {{package_name}}/jwt-header hidden false
    db_fset {{package_name}}/jwt-secret hidden false
    db_input critical {{package_name}}/jwt-header || true
    db_input critical {{package_name}}/jwt-secret || true
    db_go
else
    db_fset {{package_name}}/jwt-header hidden true
    db_fset {{package_name}}/jwt-secret hidden true
fi
