## COPY PUBLIC ##
../../../buildtools/install/common/{{product}}-ssl-setup                 usr/bin
../../../buildtools/install/docker/config/nginx/templates/*.template     etc/onlyoffice/{{product}}/openresty
../../../buildtools/install/docker/config/nginx/onlyoffice*              etc/openresty/conf.d
../../../config/nginx/onlyoffice*.conf                              etc/openresty/conf.d
../../../buildtools/install/docker/config/nginx/letsencrypt*             etc/openresty/includes
../../../config/nginx/includes/onlyoffice*.conf                     etc/openresty/includes
../../../buildtools/deploy/public/*                                      var/www/{{product}}/public
../../../buildtools/deploy/client/*                                      var/www/{{product}}/client
