#!/bin/bash
set -e

# (DS v1.1.3) Removing old nginx configs to prevent conflicts before upgrading on OpenResty.
if [ -f /etc/nginx/conf.d/onlyoffice.conf ]; then
    rm -rf /etc/nginx/conf.d/onlyoffice*
    systemctl reload nginx
fi

# (DS v3.5.0) Fix SSL reset error when updating packages
PROXY_CONF="/etc/openresty/conf.d/onlyoffice-proxy.conf"
if [ -f ${PROXY_CONF} ]; then
    cp -rf ${PROXY_CONF} ${PROXY_CONF}.save
fi

exit 0
