debian/build/langflow/{README.md,pyproject.toml,uv.lock,.venv}               var/www/{{product}}/services/langflow
debian/build/langflow/src/backend                                            var/www/{{product}}/services/langflow/src
debian/build/langflow/src/frontend/build/*                                   etc/openresty/html/langflow
debian/build/langflow/src/frontend/onlyoffice-langflow.conf                  etc/openresty/includes
