## COPY PUBLIC ##
debian/build/buildtools/install/common/{{product}}-ssl-setup                 usr/bin
debian/build/buildtools/install/docker/config/nginx/templates/*.template     etc/{{product_sysname}}/{{product}}/openresty
debian/build/buildtools/config/nginx/html/*.html                             etc/openresty/html
debian/build/buildtools/install/docker/config/nginx/{{product_sysname}}*     etc/openresty/conf.d
debian/build/buildtools/config/nginx/{{product_sysname}}*.conf               etc/openresty/conf.d
debian/build/buildtools/install/docker/config/nginx/letsencrypt*             etc/openresty/includes
debian/build/buildtools/config/nginx/includes/{{product_sysname}}*.conf      etc/openresty/includes
debian/build/publish/web/public/*                                            var/www/{{product}}/public
debian/build/publish/web/client/*                                            var/www/{{product}}/client
