[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:ASC.Monolith]
command=dotnet ASC.Monolith.dll --urls=http://0.0.0.0:5051 --'$STORAGE_ROOT'=%(ENV_APP_STORAGE_ROOT)s --ENVIRONMENT=%(ENV_ENV_EXTENSION)s --pathToConf=%(ENV_PATH_TO_CONF)s --log:dir=%(ENV_LOG_DIR)s --log:name=ASC.Monolith
directory=%(ENV_SRC_PATH)s/publish/services/backend
autorestart=true
priority=300
startsecs=10

[program:ASC.Apps.Next.js]
command=node server.js --app.port=5050 --app.hostname=0.0.0.0 --app.appsettings=%(ENV_PATH_TO_CONF)s   
directory=%(ENV_BUILD_PATH)s/apps
autorestart=true
priority=300
startsecs=10

[program:ASC.Socket.IO]
command=node server.js --app.port=9899 --app.appsettings=%(ENV_PATH_TO_CONF)s   
directory=%(ENV_SRC_PATH)s/publish/services/ASC.Socket.IO
autorestart=true
priority=300
startsecs=10

[program:ASC.SsoAuth]
command=node app.js --app.port=9834 --app.appsettings=%(ENV_PATH_TO_CONF)s   
directory=%(ENV_SRC_PATH)s/publish/services/ASC.SsoAuth
autorestart=true
priority=300
startsecs=10

[program:ASC.Identity.minified]
command=/bin/sh -c 'exec /opt/java/bin/java $JAVA_OPTS -jar %(ENV_SRC_PATH)s/publish/services/ASC.Identity.minified/app.jar --server.port=8080'
directory=%(ENV_SRC_PATH)s/publish/services/ASC.Identity.minified
autostart=true
autorestart=true
startsecs=20
priority=300
environment=JAVA_OPTS="-Xms128m -Xmx512m"
stdout_logfile=/var/log/supervisor/ASC.Identity_stdout.log
stderr_logfile=/var/log/supervisor/ASC.Identity_stderr.log

[program:openresty]
command=/usr/local/openresty/bin/openresty -g "daemon off;"
autostart=true
autorestart=true
startretries=5
stderr_logfile=/var/log/supervisor/openresty_stderr.log
stderr_logfile_maxbytes=10MB
stdout_logfile=/var/log/supervisor/openresty_stdout.log
stdout_logfile_maxbytes=10MB
priority=350
