%install
rm -rf %{buildroot}
mkdir -p "%{buildroot}%{_bindir}/"
mkdir -p "%{buildroot}%{_docdir}/%{name}-%{version}-%{release}/"
mkdir -p "%{buildroot}%{_sysconfdir}/fluent-bit/"
mkdir -p "%{buildroot}%{_sysconfdir}/onlyoffice/%{product}/.private/"
mkdir -p "%{buildroot}%{_sysconfdir}/onlyoffice/%{product}/openresty"
mkdir -p "%{buildroot}%{_sysconfdir}/openresty/conf.d/"
mkdir -p "%{buildroot}%{_sysconfdir}/openresty/html/"
mkdir -p "%{buildroot}%{_sysconfdir}/openresty/includes/"
mkdir -p "%{buildroot}%{_var}/log/onlyoffice/%{product}/"
mkdir -p "%{buildroot}%{_var}/www/onlyoffice/Data/Studio/webplugins/"
mkdir -p "%{buildroot}%{buildpath}/client/"
mkdir -p "%{buildroot}%{buildpath}/products/ASC.AI/server/"
mkdir -p "%{buildroot}%{buildpath}/products/ASC.AI/service/"
mkdir -p "%{buildroot}%{buildpath}/products/ASC.AI/mcp/"
mkdir -p "%{buildroot}%{buildpath}/products/ASC.Files/client/"
mkdir -p "%{buildroot}%{buildpath}/products/ASC.Files/editor/"
mkdir -p "%{buildroot}%{buildpath}/products/ASC.Files/server/DocStore/"
mkdir -p "%{buildroot}%{buildpath}/products/ASC.Files/service/"
mkdir -p "%{buildroot}%{buildpath}/products/ASC.Login/login/"
mkdir -p "%{buildroot}%{buildpath}/products/ASC.Management/management/"
mkdir -p "%{buildroot}%{buildpath}/products/ASC.People/client/"
mkdir -p "%{buildroot}%{buildpath}/products/ASC.People/server/"
mkdir -p "%{buildroot}%{buildpath}/products/ASC.Sdk/sdk/"
mkdir -p "%{buildroot}%{buildpath}/public/"
mkdir -p "%{buildroot}%{buildpath}/public/campaigns/"
mkdir -p "%{buildroot}%{buildpath}/services/ASC.ApiSystem/"
mkdir -p "%{buildroot}%{buildpath}/services/ASC.ClearEvents/"
mkdir -p "%{buildroot}%{buildpath}/services/ASC.Data.Backup.BackgroundTasks/"
mkdir -p "%{buildroot}%{buildpath}/services/ASC.Data.Backup/"
mkdir -p "%{buildroot}%{buildpath}/services/ASC.Identity.Authorization/"
mkdir -p "%{buildroot}%{buildpath}/services/ASC.Identity.Registration/"
mkdir -p "%{buildroot}%{buildpath}/services/ASC.Migration.Runner/"
mkdir -p "%{buildroot}%{buildpath}/services/ASC.Notify/"
mkdir -p "%{buildroot}%{buildpath}/services/ASC.Socket.IO/"
mkdir -p "%{buildroot}%{buildpath}/services/ASC.SsoAuth/"
mkdir -p "%{buildroot}%{buildpath}/services/ASC.Studio.Notify/"
mkdir -p "%{buildroot}%{buildpath}/services/ASC.TelegramService/"
mkdir -p "%{buildroot}%{buildpath}/services/ASC.Web.HealthChecks.UI/"
mkdir -p "%{buildroot}%{buildpath}/studio/ASC.Web.Api/"
mkdir -p "%{buildroot}%{buildpath}/studio/ASC.Web.Studio/"
mkdir -p "%{buildroot}/usr/lib/systemd/system/"
rsync -a --exclude='nginx' %{_builddir}/buildtools/config/ "%{buildroot}%{_sysconfdir}/onlyoffice/%{product}/"
rsync -a %{_builddir}/buildtools/config/nginx/html/ "%{buildroot}%{_sysconfdir}/openresty/html/"
rsync -a %{_builddir}/buildtools/config/nginx/includes/ "%{buildroot}%{_sysconfdir}/openresty/includes/"
rsync -a %{_builddir}/buildtools/config/nginx/onlyoffice*.conf "%{buildroot}%{_sysconfdir}/openresty/conf.d/"
rsync -a %{_builddir}/buildtools/install/common/%{product}-configuration "%{buildroot}%{_bindir}/"
rsync -a %{_builddir}/buildtools/install/common/%{product}-ssl-setup "%{buildroot}%{_bindir}/"
rsync -a %{_builddir}/buildtools/install/common/systemd/modules/ "%{buildroot}/usr/lib/systemd/system/"
rsync -a %{_builddir}/buildtools/install/docker/config/fluent-bit.conf "%{buildroot}%{_sysconfdir}/onlyoffice/%{product}/"
rsync -a %{_builddir}/buildtools/install/docker/config/nginx/letsencrypt.conf "%{buildroot}%{_sysconfdir}/openresty/includes/"
rsync -a %{_builddir}/buildtools/install/docker/config/nginx/onlyoffice* "%{buildroot}%{_sysconfdir}/openresty/conf.d/"
rsync -a %{_builddir}/buildtools/install/docker/config/nginx/templates/nginx.conf.template "%{buildroot}%{_sysconfdir}/onlyoffice/%{product}/openresty/"
rsync -a %{_builddir}/campaigns/src/campaigns/ "%{buildroot}%{buildpath}/public/campaigns/"
rsync -a %{_builddir}/plugins/publish/ "%{buildroot}%{_var}/www/onlyoffice/Data/Studio/webplugins/"
rsync -a %{_builddir}/publish/services/ASC.AI.Service/service/ "%{buildroot}%{buildpath}/products/ASC.AI/service/"
rsync -a %{_builddir}/publish/services/ASC.AI/service/ "%{buildroot}%{buildpath}/products/ASC.AI/server/"
rsync -a %{_builddir}/publish/services/ASC.AI.MCP/service/ "%{buildroot}%{buildpath}/products/ASC.AI/mcp/"
rsync -a %{_builddir}/publish/services/ASC.ApiSystem/service/ "%{buildroot}%{buildpath}/services/ASC.ApiSystem/"
rsync -a %{_builddir}/publish/services/ASC.ClearEvents/service/ "%{buildroot}%{buildpath}/services/ASC.ClearEvents/"
rsync -a %{_builddir}/publish/services/ASC.Data.Backup.BackgroundTasks/service/ "%{buildroot}%{buildpath}/services/ASC.Data.Backup.BackgroundTasks/"
rsync -a %{_builddir}/publish/services/ASC.Data.Backup/service/ "%{buildroot}%{buildpath}/services/ASC.Data.Backup/"
rsync -a %{_builddir}/publish/services/ASC.Files.Service/service/ "%{buildroot}%{buildpath}/products/ASC.Files/service/"
rsync -a %{_builddir}/publish/services/ASC.Files/service/ "%{buildroot}%{buildpath}/products/ASC.Files/server/"
rsync -a %{_builddir}/publish/services/ASC.Migration.Runner/service/ "%{buildroot}%{buildpath}/services/ASC.Migration.Runner/"
rsync -a %{_builddir}/publish/services/ASC.Notify/service/ "%{buildroot}%{buildpath}/services/ASC.Notify/"
rsync -a %{_builddir}/publish/services/ASC.People/service/ "%{buildroot}%{buildpath}/products/ASC.People/server/"
rsync -a %{_builddir}/publish/services/ASC.Studio.Notify/service/ "%{buildroot}%{buildpath}/services/ASC.Studio.Notify/"
rsync -a %{_builddir}/publish/services/ASC.TelegramService/service/ "%{buildroot}%{buildpath}/services/ASC.TelegramService/"
rsync -a %{_builddir}/publish/services/ASC.Web.Api/service/ "%{buildroot}%{buildpath}/studio/ASC.Web.Api/"
rsync -a %{_builddir}/publish/services/ASC.Web.HealthChecks.UI/service/ "%{buildroot}%{buildpath}/services/ASC.Web.HealthChecks.UI/"
rsync -a %{_builddir}/publish/services/ASC.Web.Studio/service/ "%{buildroot}%{buildpath}/studio/ASC.Web.Studio/"
rsync -a %{_builddir}/publish/web/client/ "%{buildroot}%{buildpath}/client/"
rsync -a %{_builddir}/publish/web/editor/ "%{buildroot}%{buildpath}/products/ASC.Files/editor/"
rsync -a %{_builddir}/publish/web/login/ "%{buildroot}%{buildpath}/products/ASC.Login/login/"
rsync -a %{_builddir}/publish/web/management/ "%{buildroot}%{buildpath}/products/ASC.Management/management/"
rsync -a %{_builddir}/publish/web/public/ "%{buildroot}%{buildpath}/public/"
rsync -a %{_builddir}/publish/web/sdk/ "%{buildroot}%{buildpath}/products/ASC.Sdk/sdk/"
rsync -a %{_builddir}/publish/services/ASC.Identity.Authorization/app.jar "%{buildroot}%{buildpath}/services/ASC.Identity.Authorization/app.jar"
rsync -a %{_builddir}/publish/services/ASC.Identity.Registration/app.jar "%{buildroot}%{buildpath}/services/ASC.Identity.Registration/app.jar"
rsync -a %{_builddir}/publish/services/ASC.Socket.IO/ "%{buildroot}%{buildpath}/services/ASC.Socket.IO/"
rsync -a %{_builddir}/publish/services/ASC.SsoAuth/ "%{buildroot}%{buildpath}/services/ASC.SsoAuth/"
rsync -a %{_builddir}/LICENSE "%{buildroot}%{_docdir}/%{name}-%{version}-%{release}/"
rsync -a %{_builddir}/DocStore/ "%{buildroot}%{buildpath}/products/ASC.Files/server/DocStore/"
