Vagrant.configure("2") do |config|
    config.vm.box = "#{ENV['DISTR']}/#{ENV['OS']}"

    # Slow CI runners may need more than the default 300s to boot after box import;
    config.vm.boot_timeout = 600

    config.vm.provider "virtualbox" do |v|
             v.customize ["modifyvm", :id, "--memory", "#{ENV['RAM']}"] #<= total RAM.
             v.customize ["modifyvm", :id, "--cpus", "#{ENV['CPU']}"] #<= total CPU.
             v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.define 'ubuntu'

    config.vm.hostname = "host4test"

    # Expose DocSpace to the host so smoke tests can reach it
    config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

    if ENV['DOWNLOAD_SCRIPT'] == '-ds false'
       config.vm.provision "file", source: "../../../DocSpace-buildtools/install/OneClickInstall/.", destination: "/tmp/docspace/"
    end

    config.vm.provision "file", source: "../../../DocSpace-buildtools/install/common/systemd/build.sh", destination: "/tmp/docspace/build.sh"
    config.vm.provision "shell", path: './install.sh', :args => "#{ENV['DOWNLOAD_SCRIPT']} #{ENV['TEST_REPO']} #{ENV['ARGUMENTS']}"

    # Enable synced folder for log collection
    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
end
