x-build: &x-build
  context: ../../../../DocSpace-AI
  dockerfile: Dockerfile

x-healthcheck: &x-healthcheck
  interval: 60s
  retries: 5
  start_period: 20s
  timeout: 10s

services:
  onlyoffice-ai:
    build:
      <<: *x-build
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    volumes:
      - ../../config:/app/src/config
    healthcheck:
      <<: *x-healthcheck
      test: ["CMD", "curl", "-f", "${SERVICE_AI}/api/2.0/ai/health"]

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
