x-build: &x-build
  context: ../../../../DocSpace-AI
  dockerfile: Dockerfile

x-healthcheck: &x-healthcheck
  interval: 60s
  retries: 5
  start_period: 20s
  timeout: 10s

services:
  onlyoffice-ai:
    build:
      <<: *x-build
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MYSQL_CONTAINER_NAME=${MYSQL_CONTAINER_NAME}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - RABBIT_CONTAINER_NAME=${RABBIT_CONTAINER_NAME}
      - RABBIT_PROTOCOL=${RABBIT_PROTOCOL}
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_USER_NAME=${RABBIT_USER_NAME}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - RABBIT_VIRTUAL_HOST=${RABBIT_VIRTUAL_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USER_NAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_CONTAINER_NAME=${REDIS_CONTAINER_NAME}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    volumes:
      - ../../config:/app/src/config
    healthcheck:
      <<: *x-healthcheck
      test: ["CMD", "curl", "-f", "${SERVICE_AI}/api/2.0/ai/health"]

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
