x-common-environment: &x-common-environment
  JDBC_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  JDBC_URL: ${MYSQL_HOST}
  JDBC_USER_NAME: root
  JDBC_DATABASE: ${MYSQL_DATABASE}
  RABBIT_HOST: ${RABBIT_CONTAINER_NAME}
  REDIS_HOST: ${REDIS_CONTAINER_NAME}

services:
  onlyoffice-identity-authorization:
    build:
      context: ../../../server/common/ASC.Identity
      dockerfile: ${IDENTITY_DOCKERFILE}
      args: 
        - MODULE=authorization/authorization-container
    container_name: ${IDENTITY_AUTHORIZATION_CONTAINER_NAME}
    restart: always
    ports:
      - "${IDENTITY_AUTHORIZATION_SERVER_PORT}:${IDENTITY_AUTHORIZATION_SERVER_PORT}"
    environment:
      <<: *x-common-environment
      SPRING_PROFILES_ACTIVE: ${IDENTITY_PROFILE}
      SPRING_APPLICATION_NAME: ASC.Identity.Authorization
      SERVER_PORT: ${IDENTITY_AUTHORIZATION_SERVER_PORT}
    depends_on:
      - onlyoffice-identity-migration

  onlyoffice-identity-api:
    build:
      context: ../../../server/common/ASC.Identity
      dockerfile: ${IDENTITY_DOCKERFILE}
      args: 
        - MODULE=registration/registration-container
    container_name: ${IDENTITY_API_CONTAINER_NAME}
    ports:
      - "${IDENTITY_API_SERVER_PORT}:${IDENTITY_API_SERVER_PORT}"
    environment:
      <<: *x-common-environment
      SPRING_PROFILES_ACTIVE: ${IDENTITY_PROFILE}
      SPRING_APPLICATION_NAME: ASC.Identity.Registration
      SERVER_PORT: ${IDENTITY_API_SERVER_PORT}
    depends_on:
      - onlyoffice-identity-migration

  onlyoffice-identity-migration:
    build:
      context: ../../../server/common/ASC.Identity
      dockerfile: ${IDENTITY_DOCKERFILE}
      args: 
        - MODULE=infrastructure/infrastructure-migration-runner
    container_name: ${IDENTITY_MIGRATION_CONTAINER_NAME} 
    restart: "no"
    ports:
      - "${IDENTITY_MIGRATION_SERVER_PORT}:${IDENTITY_MIGRATION_SERVER_PORT}"
    environment:
      <<: *x-common-environment

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
