services:
  onlyoffice-mysql-server:
    image: ${MYSQL_IMAGE}
    cap_add:
      - SYS_NICE
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: always
    tty: true
    user: mysql
    expose:
      - "3306"
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/mysql/conf.d/:/etc/mysql/conf.d
    networks:
      - ${NETWORK_NAME}

networks:
  onlyoffice:
    name: ${NETWORK_NAME}
    driver: "bridge"
    external: true

volumes:
  mysql_data:
