#!/bin/bash 

SPRING_APPLICATION_NAME="${1}"

JDBC_URL=${MYSQL_HOST:-${MYSQL_CONTAINER_NAME}}
JDBC_DATABASE=${MYSQL_DATABASE:-"onlyoffice"}
JDBC_USER_NAME=${MYSQL_USER:-"onlyoffice_user"}
JDBC_PASSWORD=${MYSQL_PASSWORD:-"onlyoffice_pass"}

REDIS_HOST=${REDIS_HOST:-${REDIS_CONTAINER_NAME}}
REDIS_PORT=${REDIS_PORT:-"6379"}

RABBIT_URI="${RABBIT_PROTOCOL:-"amqp"}://${RABBIT_USER_NAME:-"guest"}:${RABBIT_PASSWORD:-"guest"}${RABBIT_HOST:-${RABBIT_CONTAINER_NAME}}${RABBIT_VIRTUAL_HOST:-"/"}"

LOG_FILE_PATH=${LOG_DIR:-"/var/log/onlyoffice/"}

java -jar ${BUILD_PATH}/services/${SPRING_APPLICATION_NAME}/app.jar
