x-healthcheck: &x-healthcheck
  interval: 60s
  retries: 5
  start_period: 20s
  timeout: 10s

x-common-environment: &x-common-environment
  JDBC_PASSWORD: ${MYSQL_PASSWORD}
  JDBC_URL: ${MYSQL_HOST}
  JDBC_USER_NAME: ${MYSQL_USER}
  JDBC_DATABASE: ${MYSQL_DATABASE}
  RABBIT_HOST: ${RABBIT_HOST}
  REDIS_HOST: ${REDIS_HOST}

services:
  onlyoffice-identity-authorization:
    image: "${HUB}${REPO}/${DOCKER_IMAGE_PREFIX}-identity-authorization:${DOCKER_TAG}"
    container_name: ${IDENTITY_AUTHORIZATION_CONTAINER_NAME}
    restart: always
    ports:
      - "${IDENTITY_AUTHORIZATION_SERVER_PORT}:${IDENTITY_AUTHORIZATION_SERVER_PORT}"
    environment:
      <<: *x-common-environment
      SPRING_PROFILES_ACTIVE: ${IDENTITY_PROFILE}
      SPRING_APPLICATION_NAME: ASC.Identity.Authorization
      SERVER_PORT: ${IDENTITY_AUTHORIZATION_SERVER_PORT}
    healthcheck:
      <<: *x-healthcheck
      test: curl --fail ${SERVICE_IDENTITY}/health/ || exit 1
    depends_on:
      - onlyoffice-identity-migration

  onlyoffice-identity-api:
    image: "${HUB}${REPO}/${DOCKER_IMAGE_PREFIX}-identity-api:${DOCKER_TAG}"
    container_name: ${IDENTITY_API_CONTAINER_NAME}
    ports:
      - "${IDENTITY_API_SERVER_PORT}:${IDENTITY_API_SERVER_PORT}"
    restart: always
    environment:
      <<: *x-common-environment
      SPRING_PROFILES_ACTIVE: ${IDENTITY_PROFILE}
      SPRING_APPLICATION_NAME: ASC.Identity.Registration
      SERVER_PORT: ${IDENTITY_API_SERVER_PORT}
    healthcheck:
      <<: *x-healthcheck
      test: curl --fail ${SERVICE_IDENTITY_API}/health/ || exit 1
    depends_on:
      - onlyoffice-identity-migration

  onlyoffice-identity-migration:
    image: "${HUB}${REPO}/${DOCKER_IMAGE_PREFIX}-identity-migration:${DOCKER_TAG}"
    container_name: ${IDENTITY_MIGRATION_CONTAINER_NAME}
    restart: on-failure
    ports:
      - "${IDENTITY_MIGRATION_SERVER_PORT}:${IDENTITY_MIGRATION_SERVER_PORT}"
    environment:
      <<: *x-common-environment

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
