x-common-environment: &common-environment
  JDBC_PASSWORD: ${JDBC_PASSWORD}
  JDBC_URL: ${JDBC_URL}
  JDBC_USER_NAME: ${JDBC_USER_NAME}
  JDBC_DATABASE: ${JDBC_DATABASE}
  RABBIT_HOST: ${RABBIT_CONTAINER_NAME}
  REDIS_HOST: ${REDIS_CONTAINER_NAME}

services:
  onlyoffice-identity-authorization:
    image: "${HUB}${REPO}/${DOCKER_IMAGE_PREFIX}-identity-authorization:${DOCKER_TAG}"
    container_name: ${IDENTITY_AUTHORIZATION_CONTAINER_NAME}
    restart: always
    ports:
      - "${IDENTITY_AUTHORIZATION_SERVER_PORT}:${IDENTITY_AUTHORIZATION_SERVER_PORT}"
    environment:
      <<: *common-environment
      SPRING_PROFILES_ACTIVE: ${IDENTITY_PROFILE}
      SPRING_APPLICATION_NAME: ASC.Identity.Authorization
      SERVER_PORT: ${IDENTITY_AUTHORIZATION_SERVER_PORT}
    depends_on:
      - onlyoffice-identity-migration

  onlyoffice-identity-api:
    image: "${HUB}${REPO}/${DOCKER_IMAGE_PREFIX}-identity-api:${DOCKER_TAG}"
    container_name: ${IDENTITY_API_CONTAINER_NAME}
    ports:
      - "${IDENTITY_API_SERVER_PORT}:${IDENTITY_API_SERVER_PORT}"
    environment:
      <<: *common-environment
      SPRING_PROFILES_ACTIVE: ${IDENTITY_PROFILE}
      SPRING_APPLICATION_NAME: ASC.Identity.Registration
      SERVER_PORT: ${IDENTITY_API_SERVER_PORT}
    depends_on:
      - onlyoffice-identity-migration

  onlyoffice-identity-migration:
    image: "${HUB}${REPO}/${DOCKER_IMAGE_PREFIX}-identity-migration:${DOCKER_TAG}"
    container_name: ${IDENTITY_MIGRATION_CONTAINER_NAME}
    restart: on-failure
    ports:
      - "${IDENTITY_MIGRATION_SERVER_PORT}:${IDENTITY_MIGRATION_SERVER_PORT}"
    environment:
      <<: *common-environment

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
