version: "3.8"

services:
  onlyoffice-identity-authorization:
    build:
      context: ../../../server/common/ASC.Identity
      dockerfile: ${IDENTITY_DOCKERFILE}
      args: 
        - MODULE=authorization/authorization-container
    container_name: ${IDENTITY_AUTHORIZATION_CONTAINER_NAME}
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=${IDENTITY_PROFILE}
      - SPRING_APPLICATION_NAME=ASC.Identity.Authorization
      - SERVER_PORT=${IDENTITY_AUTHORIZATION_SERVER_PORT}
      - JDBC_PASSWORD=${JDBC_PASSWORD}
      - JDBC_URL=${JDBC_URL}
      - JDBC_USER_NAME=${JDBC_USER_NAME}
      - JDBC_DATABASE=${JDBC_DATABASE}
      - RABBIT_HOST=onlyoffice-rabbitmq
      - REDIS_HOST=onlyoffice-redis
    depends_on:
      - onlyoffice-identity-migration

  onlyoffice-identity-api:
    build:
      context: ../../../server/common/ASC.Identity
      dockerfile: ${IDENTITY_DOCKERFILE}
      args: 
        - MODULE=registration/registration-container
    container_name: ${IDENTITY_API_CONTAINER_NAME}
    ports:
      - 9090:9090
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}
      - SPRING_APPLICATION_NAME=ASC.Identity.Registration
       - SERVER_PORT=${IDENTITY_API_SERVER_PORT}
      - JDBC_PASSWORD=${JDBC_PASSWORD}
      - JDBC_URL=${JDBC_URL}
      - JDBC_USER_NAME=${JDBC_USER_NAME}
      - JDBC_DATABASE=${JDBC_DATABASE}
      - RABBIT_HOST=onlyoffice-rabbitmq
      - REDIS_HOST=onlyoffice-redis
    depends_on:
      - onlyoffice-identity-migration

  onlyoffice-identity-migration:
    build:
      context: ../../../server/common/ASC.Identity
      dockerfile: ${IDENTITY_DOCKERFILE}
      args: 
        - MODULE=infrastructure/infrastructure-migration-runner
    container_name: ${IDENTITY_MIGRATION_CONTAINER_NAME} 
    restart: "no"
    ports:
      - 8081:8081
    environment:
      - JDBC_PASSWORD=${JDBC_PASSWORD}
      - JDBC_URL=${JDBC_URL}
      - JDBC_USER_NAME=${JDBC_USER_NAME}
      - JDBC_DATABASE=${JDBC_DATABASE}
      - RABBIT_HOST=onlyoffice-rabbitmq
      - REDIS_HOST=onlyoffice-redis
networks:
  default:
    name: ${NETWORK_NAME}
    external: true
