version: "3.8"

services:
  onlyoffice-qdrant-server:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    environment:
      - QDRANT_ALLOW_RECOVERY=true
      - QDRANT_TELEMETRY_DISABLED=true

networks:
  default:
    name: ${NETWORK_NAME}
    external: true
