services:
  onlyoffice-rabbitmq:
    image: ${HUB}${RABBITMQ_IMAGE_NAME}:${RABBITMQ_VERSION}
    container_name: ${RABBIT_CONTAINER_NAME}
    restart: always
    expose:
      - "5672"
      - "80"
networks:
  default:
    name: ${NETWORK_NAME}
    external: true
