[supervisord]
nodaemon=true
logfile=%(ENV_LOG_DIR)s/supervisord_java.log
loglevel=warn

[program:ASC.Identity.Authorization]
command=java -jar app.jar
directory=%(ENV_BUILD_PATH)s/services/ASC.Identity.Authorization
environment=SPRING_APPLICATION_NAME="ASC.Identity.Authorization",LOG_FILE_PATH="%(ENV_LOG_DIR)s/ASC.Identity.Authorization.log",SERVER_PORT="%(ENV_IDENTITY_AUTHORIZATION_SERVER_PORT)s"
autorestart=true
startsecs=25

[program:ASC.Identity.Registration]
command=java -jar app.jar
directory=%(ENV_BUILD_PATH)s/services/ASC.Identity.Registration
environment=SPRING_APPLICATION_NAME="ASC.Identity.Registration",LOG_FILE_PATH="%(ENV_LOG_DIR)s/ASC.Identity.Registration.log",SERVER_PORT="%(ENV_IDENTITY_API_SERVER_PORT)s"
autorestart=true
startsecs=25
