name: 4testing multiarch-cron-build

on:
  schedule:
    - cron: '0 20 * * *'

jobs:
  call-cron-build:
    uses: ONLYOFFICE/DocSpace-buildtools/.github/workflows/reusable-cron.yml@master
    with:
      organization: 'ONLYOFFICE'
      repository: 'DocSpace-buildtools'
    secrets:
      git-user: ${{ secrets.USERNAME }}
      git-token: ${{ secrets.TOKEN }}
